# Generated by Django 4.0.4 on 2022-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0002_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(verbose_name=True),
        ),
    ]
